tsconfig.json:
  compilerOptions:
    baseUrl: '.'
    outDir: dist
    rootDir: src

    module: commonjs
    target: es6
    lib:
      - es2017
      - es2018
      - esnext

    sourceMap: false
    allowJs: true

    moduleResolution: node

    strict: true
    alwaysStrict: true
    noUnusedLocals: true
    noImplicitThis: true
    noUnusedParameters: true
    noImplicitReturns: true
    forceConsistentCasingInFileNames: true
    suppressImplicitAnyIndexErrors: true

package.json:
  name: misexnuk
  version: 1.0.0
  author: Xnuk Shuman
  license: BSD-3-Clause

  scripts:
    run: ts-node app/run.ts

  dependencies:
    axios: ^0.18.0
    dotenv: ^6.2.0
    twit: ^2.2.11
    redis: ^2.8.0

  devDependencies:
    '@types/node': ^10.12.12
    '@types/twit': ^2.2.20
    '@types/redis': ^2.8.8
    ts-node: ^7.0.1
    typescript: ^3.2.2
