version: 2.1
jobs:
  build:
    docker:
      - image: node:current
      - image: redis:latest

    steps:
      - run: apt-get update && apt-get install -y ruby
      - checkout

      - restore_cache:
          keys:
            - t1-node-modules-{{ arch }}-{{ checksum "package-lock.json" }}

      - run: npm run setup

      - run: npm run build

      - save_cache:
          key: t1-node-modules-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - build
